import express from 'express';
import { CourseController } from './course.controller';
const router = express.Router();
router.get('/:id', CourseController.getByIdFromDB);
router.delete('/:id', CourseController.deleteByIdFromDB);
router.patch('/:id', CourseController.updateOneIntoDB);
router.post('/:id/assign-faculties', CourseController.assignFaculty);
router.delete('/:id/remove-faculties', CourseController.removeFaculty);
router.post('/', CourseController.insertIntoDB);
router.get('/', CourseController.getAllFromDB);
export const CourseRoutes = router;
